trigger:
 branches:
   include:
     - main
     - feature/*

pool: 
 name: pipeline-agent


stages:
  - stage: pre_build
    displayName: pre build
    jobs: 
      - job: tf_setup
        pool: pipeline-agent
        displayName: tf_setup
        steps:
        - task: TerraformInstaller@1
          displayName: tf_setup
          inputs:
            terraformVersion: 'latest'
      - job: prebuild
        dependsOn: tf_setup
        displayName: terraform plan
        steps:
        - task: TerraformTask@5
          displayName: tf init
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'pileline-sc'
            backendAzureRmStorageAccountName: 'tfbackendstg123'
            backendAzureRmContainerName: 'tfstate'
            backendAzureRmKey: 'dev.terraform.tfstate'

        - task: TerraformTask@5
          displayName: tf plan
          inputs:
            provider: 'azurerm'
            command: 'plan'
            environmentServiceNameAzureRM: 'pileline-sc'





